### ISSUE TITLE
Add geospatial information about models

### ISSUE THREAD

**Issue by dgarijo** [mintproject/ModelCatalog#28]
We have region name and country, but not the geojson associated to models. We should have this info so we can support geospatial queries in models (or at least based on bounding boxes)

**Comment by hvarg** [comment]
The current version has bounding boxes for all regions.
Geojson are long strings, we already have these on the MINT-UI database so I think we do not need to add them in the model-catalog (unless we need to use it)

**Comment by dgarijo** [comment]
We already added bounding boxes, we can close this issue. Thanks!
