### ISSUE TITLE
Incomplete data for some resources

### ISSUE THREAD

**Issue by hvarg** [mintproject/ModelCatalog#34]
We should use this issue to report any resource with missing data.

I've found:
https://w3id.org/okn/i/mint/DSSAT_cfg_simple_TI
https://w3id.org/okn/i/mint/hand_grid_ethiopia
https://w3id.org/okn/i/mint/kimetrica_land_use_cfg_simple (missing `intervalUnit` and `intervalValue`)
https://w3id.org/okn/i/mint/swat_grid (missing `sdm:hasDimension` and `sdm:hasSpatialResolution`)

some grids are missing `sdm:hasShape`, it's optional?

**Comment by dgarijo** [comment]
Thanks for reporting this. In some cases, it's just that I don't know this information. I may delete these resources. HasShape is optional

**Comment by dgarijo** [comment]
I have fixed this in the latest commit (https://github.com/mintproject/ModelCatalog/commit/127ae81468878c6e0dfe4f80d4db6a530c0312be)
