### ISSUE TITLE
Parse sd:hasAssumption

### ISSUE THREAD

**Issue by hvarg** [mintproject/ModelCatalog#35]
In the MINT-UI we are displaying `sd:hasAssumption` as a list, for this we are parsing the dots of the string but `.` is not a good delimiter.

I propose to change the delimiter to `;` if we want to display this information as a list on the UI.

**Comment by dgarijo** [comment]
You are right. I will try to make the assumptions separate you don't have to do this. Basically, it will return an array instead of a single object

**Comment by dgarijo** [comment]
I added some delimeters. Please give a try. Fixed in https://github.com/mintproject/ModelCatalog/commit/127ae81468878c6e0dfe4f80d4db6a530c0312be
