### ISSUE TITLE
missing data of some resources

### ISSUE THREAD

**Issue by hvarg** [mintproject/ModelCatalog#38]
The following resources are being used but have no data:
https://w3id.org/okn/i/mint/somer_philipp
https://w3id.org/okn/i/mint/engel_bernard https://rdfexplorer.mint.isi.edu/page/okn/i/mint/kaplan_jed

**Comment by mosoriob** [comment]
There is a typo in the topoflow model.
https://w3id.org/okn/i/mint/TOPOFLOW
https://w3id.org/okn/o/sd#hasContactPerson
https://w3id.org/okn/i/mint/pecham_scot

```
======================================================================
FAIL: Test case for model_get
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mosorio/repos/work/model-catalog-api/server/openapi_server/test/test_model_controller.py", line 100, in test_model_custom_region_get
    'Response body is : ' + response.data.decode('utf-8'))
  File "/Users/mosorio/repos/work/model-catalog-api/server/.tox/py3/lib/python3.7/site-packages/flask_testing/utils.py", line 310, in assert200
    self.assertStatus(response, 200, message)
  File "/Users/mosorio/repos/work/model-catalog-api/server/.tox/py3/lib/python3.7/site-packages/flask_testing/utils.py", line 298, in assertStatus
    self.assertEqual(response.status_code, status_code, message)
AssertionError: 500 != 200 : Response body is : {
  "detail": "'https://w3id.org/okn/i/mint/pecham_scott' is not of type 'object'\n\nFailed validating 'type' in schema['items']['properties']['hasContactPerson']['items']:\n    {'type': 'object'}\n\nOn instance[2]['hasContactPerson'][0]:\n    'https://w3id.org/okn/i/mint/pecham_scott'",
  "status": 500,
  "title": "Response body does not conform to specification",
  "type": "about:blank"
}
```

**Comment by mosoriob** [comment]
More resources:

https://w3id.org/okn/i/mint/biomassgrowth
https://w3id.org/okn/i/mint/penn_state

**Comment by dgarijo** [comment]
Should be fixed now (some of these entities have been deleted)

**Comment by mosoriob** [comment]
The tests found another issue:
https://rdfexplorer.mint.isi.edu/page/okn/i/mint/management

You can run the test using travis 
https://travis-ci.com/github/mintproject/model-catalog-api

or:

https://github.com/mintproject/model-catalog-api/blob/master/README.md#testing

**Comment by mosoriob** [comment]
By manual inspection.

https://w3id.org/okn/i/mint/management
https://w3id.org/okn/i/mint/humification
https://w3id.org/okn/i/mint/cycles_solarradiation
https://w3id.org/okn/i/mint/respiration
https://w3id.org/okn/i/mint/Nuptake
https://w3id.org/okn/i/mint/Nmineralizationandimmobalization
https://w3id.org/okn/i/mint/Ntransport

**Comment by dgarijo** [comment]
The tests run on the whole KG? This is ok (and desired) here, but usually not scalable in bigger KGs

**Comment by mosoriob** [comment]
Yes (for the model catalog). It takes 147 seconds.

**Comment by dgarijo** [comment]
Should be ready to go.

**Comment by mosoriob** [comment]
Nop
https://w3id.org/okn/i/mint/crop_yield
https://w3id.org/okn/i/mint/crop_supply
https://w3id.org/okn/i/mint/fertilizer_use
https://w3id.org/okn/i/mint/land_use
https://w3id.org/okn/i/mint/fertilizer_prices
https://w3id.org/okn/i/mint/crop_prices
https://w3id.org/okn/i/mint/crop_yield_elasticity

**Comment by dgarijo** [comment]
All fixed

**Comment by mosoriob** [comment]
You did it!
```
----------------------------------------------------------------------
Ran 53 tests in 155.485s

OK
__________________________________________________________________________ summary __________________________________________________________________________
  py3: commands succeeded
  congratulations :)
```
