### ISSUE TITLE
Icons for epidemiology models

### ISSUE THREAD

**Issue by hvarg** [mintproject/ModelCatalog#43]
We need to add some temporal icons for the epidemiology models.

For SIR:
![SIR](https://user-images.githubusercontent.com/15269912/78955911-b6eb6600-7aae-11ea-8c1d-982b9d177d62.gif)

For IHME:
<img width="712" alt="IHME" src="https://user-images.githubusercontent.com/15269912/78955926-beab0a80-7aae-11ea-83e6-430b0920235d.png">

**Comment by dgarijo** [comment]
Where do these images come from? We should credit them

**Comment by dgarijo** [comment]
I added the logos from the model source
